<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

 // Remove where the Category title is placed
  remove_action( 'genesis_before_loop', 'genesis_do_taxonomy_title_description', 15 );

// Add the Category image ACF field
add_action( 'genesis_before_content_sidebar_wrap', 'add_category_image_acf', 5);

function add_category_image_acf() {

           $queried_object = get_queried_object();
           $taxonomy = $queried_object->taxonomy;
           $term_id = $queried_object->term_id;

           $image = get_field('category_image', $taxonomy . '_' . $term_id);

           if( !empty($image) ) {
           ?>
           <div class="category-featured-image" style="background-image: url('<?php echo $image['url']; ?>')">
           <?php
         }
}


// Add title back in
 add_action( 'genesis_before_content_sidebar_wrap', 'genesis_do_taxonomy_title_description', 15);

 // Add the close div tag for the category image
 add_action( 'genesis_before_content_sidebar_wrap', 'laura_close_div', 15);

  function laura_close_div() {
          ?>
      </div>
        <?php
  }


// Fix up the loop
remove_action( 'genesis_entry_header', 'genesis_do_post_title' );
remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );
remove_action( 'genesis_entry_content', 'genesis_do_post_image', 8 );
remove_action( 'genesis_entry_footer', 'genesis_post_meta' );

add_action( 'genesis_entry_header', 'genesis_do_post_image');

add_action( 'genesis_before_entry_content', 'laura_entry');

function laura_entry() {

  echo '<div class="post-text">';
  echo '<h4><a href="' . get_the_permalink() .'">'. get_the_title() . '</a></h4>';
}

add_action('genesis_entry_footer', 'laura_read_more');

function laura_read_more() {
  echo '<p class="readmorelink"><a href=" '.get_the_permalink() . '">READ MORE&nbsp<i class="fas fa-angle-double-right"></i></a></p></div>';

}


// Initialize Genesis.
genesis();
