<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */


 add_action ('genesis_before_content_sidebar_wrap', 'laura_blog_header');

 function laura_blog_header() {

   $laura_posts_page = get_option( 'page_for_posts' );

   $laurablogpage = get_the_title( $laura_posts_page );
     ?>
         <h1 class="page-header"><?php
         echo $laurablogpage;
       ?></h1>
     <?php

 }


remove_action( 'genesis_entry_header', 'genesis_do_post_title' );
remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );
remove_action( 'genesis_entry_content', 'genesis_do_post_image', 8 );
remove_action( 'genesis_entry_footer', 'genesis_post_meta' );

add_action( 'genesis_entry_header', 'genesis_do_post_image');

add_action( 'genesis_before_entry_content', 'laura_entry');

function laura_entry() {

  echo '<div class="post-text">';
  echo '<h4><a href="' . get_the_permalink() .'">'. get_the_title() . '</a></h4>';
}

add_action('genesis_entry_footer', 'laura_read_more');

function laura_read_more() {
  echo '<p class="readmorelink"><a href=" '.get_the_permalink() . '">READ MORE&nbsp<i class="fas fa-angle-double-right"></i></a></p></div>';

}



// Initialize Genesis.
genesis();
