<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles pages, but only exists for the sake of child theme forward compatibility.


add_action ('genesis_before_content_sidebar_wrap', 'laura_page_header');

function laura_page_header() {

  if ( has_post_thumbnail() ) {
    $featured_image = wp_get_attachment_image_src(get_post_thumbnail_id(), $size = 'large');
    ?>

    <div class="laura-page-header2" style="background-image:url('<?php echo $featured_image[0] ?>')">
      <?php
    }

    else {
      ?>
        <div class="laura-page-header2">
          <?php
        }

    ?>
        <h1 class="page-header"><?php
        echo get_the_title();
      ?></h1>
    </div>
    <?php

}


remove_action( 'genesis_entry_header', 'genesis_do_post_title' );
remove_action( 'genesis_entry_header', 'genesis_entry_header_markup_open', 5 );
remove_action( 'genesis_entry_header', 'genesis_entry_header_markup_close', 15 );



genesis();
